pipeline {
    agent any
    stages {
        stage('Pull latest image') {
            steps{
				bat "docker pull nitinmanojkumar/selenium-docker:latest"
			}
        }
        stage('Start the grid using compose file') {
            steps {
                bat "docker-compose -f docker-runner/docker-compose.yaml up -d selenium-hub chrome firefox"
            }
        }
		stage('Start the execution using compose file') {
            steps {
                bat "docker-compose -f docker-runner/docker-compose.yaml up search-module book-flight-module"
            }
        }
    }
	post{
		always{
			archiveArtifacts artifacts: 'output/**'
			bat "docker-compose -f docker-runner/docker-compose.yaml down"
		}
	}
}